### ISSUE TITLE
安装后运行报错，环境是python3.7

### ISSUE THREAD

**Issue by breeef** [SOVLOOKUP/FastDocx#3]
File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "C:\Users\le\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fastdocx-0.1.3-py3.7.egg\fastdocx\core.py", line 39
    if (id := config.get("id")) == None:
           ^
SyntaxError: invalid syntax

**Comment by breeef** [comment]
Traceback (most recent call last):
  File "gendoc.py", line 1, in <module>
    import fastdocx
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\le\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fastdocx-0.1.3-py3.7.egg\fastdocx\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "C:\Users\le\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fastdocx-0.1.3-py3.7.egg\fastdocx\core.py", line 39
    if (id := config.get("id")) == None:
           ^
SyntaxError: invalid syntax

**Comment by SOVLOOKUP** [comment]
这里用到了 Python3.9 的语法，所以py3.7运行有问题 明天有时间我会修改降级再发布fastdocx

**Comment by SOVLOOKUP** [comment]
已经修复，安装最新版本的fastdocx即可

`pip install fastdocx==0.2.0 -i https://pypi.Python.org/simple/`
